version: "3.7"

volumes:
  pihole-logs: {}
  acme-data: {}

services:
  coredns:
    container_name: coredns
    image: coredns/coredns
    environment:
      AUTHORITATIVE_DNS: ${AUTHORITATIVE_DNS}
    volumes:
      - ./Corefile:/Corefile:ro
    networks:
      backend:
        ipv4_address: 172.28.241.8
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole
    hostname: ${PIHOLE_HOSTNAME}
    ports:
    - "${DNS_INTERFACE_IPV4}:53:53/tcp"
    - "${DNS_INTERFACE_IPV4}:53:53/udp"
    environment:
      TZ: 'Europe/London'
      DNS1: '172.28.241.8'
      DNS2: '172.28.241.8'
      WEBPASSWORD: "${PIHOLE_PASSWORD}"
    dns:
      - 172.28.241.8
    networks:
      frontend:
      backend:
        ipv4_address: 172.28.241.10
    volumes:
      - pihole-logs:/var/log:rw
    depends_on:
      - coredns
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.docker.network: "frontend"
      traefik.frontend.rule: "Host:${PIHOLE_HOSTNAME}.${DOMAIN}; PathPrefix:/admin"

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      CLEANUP: 'true'
      CRON: '0 3 * * *'
      LOG_LEVEL: info
      SELF_UPDATE: 'true'
      TZ: Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  traefik:
    container_name: traefik
    image: traefik
    command:
      - --acme.email=${CLOUDFLARE_API_EMAIL}
      - --acme.domains=${PIHOLE_HOSTNAME}.${DOMAIN}
      - --docker.domain=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_API_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    networks:
      frontend:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - acme-data:/acme
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.docker.network: "frontend"
      traefik.frontend.rule: "Host:${PIHOLE_HOSTNAME}.${DOMAIN}; PathPrefixStrip:/traefik"

networks:
  frontend:
    name: frontend
    ipam:
      config:
        - subnet: 172.28.240.0/24
  backend:
    name: backend
    ipam:
      config:
        - subnet: 172.28.241.0/24
